# Ruff configuration
[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "W", "F", "I"]  # Basic errors, warnings, pyflakes, import sorting

[tool.ruff.lint.isort]
known-first-party = ["lib"]

# mypy configuration
[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
warn_unused_ignores = true

# pytest configuration
[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--cov=lib", "--cov-report=html", "--cov-report=term-missing", "--cov-report=xml", "--cov-fail-under=100"]

# Coverage configuration
[tool.coverage.run]
data_file = ".coverage/data"

[tool.coverage.html]
directory = ".coverage/htmlcov"

[tool.coverage.xml]
output = ".coverage/coverage.xml"

[tool.coverage.report]
fail_under = 100
include = ["lib/*"]
