name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
        make install-dev

    - name: Run all checks and tests
      run: make all

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./.coverage/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
